import "./globals.css"
import localFont from 'next/font/local'
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({
  display: 'swap',
  subsets: [ 'latin' ],
  weight: ['300', '400', '500', '600', '700', '800' ],
  variable: '--font-open-sans',
})

const podcastFont  = localFont({
  src: './fonts/Podcast.otf',
  display: 'swap',
})

export const metadata = {
  title: "Tuscany",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${podcastFont .className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
